/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package que3;

/**
 *
 * @author KANI
 */
public class frame3 extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form frame3
     */
    Thread t;
    volatile boolean value = true;
    String s = "0";
    String m = "0";
    String mi = "0";

    public frame3() {
        initComponents();
        t = new Thread(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new java.awt.Panel();
        pnlheading = new java.awt.Panel();
        label1 = new java.awt.Label();
        lblmin = new java.awt.Label();
        lblsec = new java.awt.Label();
        lblmili = new java.awt.Label();
        pnlmin = new java.awt.Panel();
        lblminvalue = new java.awt.Label();
        pnlsec = new java.awt.Panel();
        lblsecfinal = new java.awt.Label();
        pnlmili = new java.awt.Panel();
        lblmilifinal = new java.awt.Label();
        button1 = new java.awt.Button();
        btnreset = new java.awt.Button();
        btnstop1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmain.setBackground(new java.awt.Color(0, 153, 153));

        pnlheading.setBackground(new java.awt.Color(51, 255, 255));

        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(25, 130, 202));
        label1.setText("STOPWATCH");

        javax.swing.GroupLayout pnlheadingLayout = new javax.swing.GroupLayout(pnlheading);
        pnlheading.setLayout(pnlheadingLayout);
        pnlheadingLayout.setHorizontalGroup(
            pnlheadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadingLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlheadingLayout.setVerticalGroup(
            pnlheadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlheadingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        lblmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblmin.setForeground(new java.awt.Color(51, 255, 255));
        lblmin.setText("Minutes");

        lblsec.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblsec.setForeground(new java.awt.Color(51, 255, 255));
        lblsec.setText("Seconds");

        lblmili.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblmili.setForeground(new java.awt.Color(51, 255, 255));
        lblmili.setText("MiliSeconds");

        pnlmin.setBackground(new java.awt.Color(51, 255, 255));

        lblminvalue.setAlignment(java.awt.Label.CENTER);
        lblminvalue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblminvalue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlminLayout = new javax.swing.GroupLayout(pnlmin);
        pnlmin.setLayout(pnlminLayout);
        pnlminLayout.setHorizontalGroup(
            pnlminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblminvalue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlminLayout.setVerticalGroup(
            pnlminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblminvalue, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlsec.setBackground(new java.awt.Color(51, 255, 255));

        lblsecfinal.setAlignment(java.awt.Label.CENTER);
        lblsecfinal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblsecfinal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlsecLayout = new javax.swing.GroupLayout(pnlsec);
        pnlsec.setLayout(pnlsecLayout);
        pnlsecLayout.setHorizontalGroup(
            pnlsecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsecfinal, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        pnlsecLayout.setVerticalGroup(
            pnlsecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblsecfinal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pnlmili.setBackground(new java.awt.Color(51, 255, 255));

        lblmilifinal.setAlignment(java.awt.Label.CENTER);
        lblmilifinal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout pnlmiliLayout = new javax.swing.GroupLayout(pnlmili);
        pnlmili.setLayout(pnlmiliLayout);
        pnlmiliLayout.setHorizontalGroup(
            pnlmiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmilifinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlmiliLayout.setVerticalGroup(
            pnlmiliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmilifinal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        button1.setBackground(new java.awt.Color(255, 51, 0));
        button1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 0));
        button1.setLabel("START");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 51, 0));
        btnreset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 0));
        btnreset.setLabel("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnstop1.setBackground(new java.awt.Color(255, 51, 0));
        btnstop1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnstop1.setForeground(new java.awt.Color(255, 255, 0));
        btnstop1.setLabel("STOP");
        btnstop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstop1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlheading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(lblsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(pnlmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnstop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlmili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlheading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlmili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        t = new Thread(this);
        t.start();
    }//GEN-LAST:event_button1ActionPerformed

    private void btnstop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstop1ActionPerformed
        // TODO add your handling code here:
        value = false;
        s = lblsecfinal.getText();
        m = lblminvalue.getText();
        mi = lblmilifinal.getText();
    }//GEN-LAST:event_btnstop1ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        value = false;
        lblmilifinal.setText(0 + "");
        lblsecfinal.setText(0 + "");
        lblminvalue.setText(0 + "");
        s = 0 + "";
        m = 0 + "";
        mi = 0 + "";
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnreset;
    private java.awt.Button btnstop1;
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label lblmili;
    private java.awt.Label lblmilifinal;
    private java.awt.Label lblmin;
    private java.awt.Label lblminvalue;
    private java.awt.Label lblsec;
    private java.awt.Label lblsecfinal;
    private java.awt.Panel pnlheading;
    private java.awt.Panel pnlmain;
    private java.awt.Panel pnlmili;
    private java.awt.Panel pnlmin;
    private java.awt.Panel pnlsec;
    // End of variables declaration//GEN-END:variables

    public void run() {
        long mili, sec, min;
        long ct;
        ct = System.currentTimeMillis();
        int longmili, longsec, longmin;
        longmili = Integer.parseInt(mi);
        longmin = Integer.parseInt(m);
        longsec = Integer.parseInt(s);
        while (value) {
            mili = longmili + (System.currentTimeMillis() - ct) / 100 % 10;
            sec = longsec + (System.currentTimeMillis() - ct) / 1000 % 60;
            min = longmin + ((System.currentTimeMillis() - ct) / 1000) / 60;

            lblmilifinal.setText(mili + "");
            lblsecfinal.setText(sec + "");
            lblminvalue.setText(min + "");
            try {
                Thread.sleep(100);
            } catch (Exception e) {

            }

        }
        value = true;
    }
}
